### PR TITLE
feat(search): introduce keymap-dependent vim-mode

### PR DESCRIPTION
**Pull request by akinomyoga**
This is a possible refinement to the vim mode as suggested in https://github.com/atuinsh/atuin/pull/1553#issuecomment-1890426150.

In this PR, we introduce three keymap modes, `emacs`, `vim-insert`, and `vim-normal` (which was extended from the current `VimMode`). When the config `vim` is enabled, the keys are processed with special rules for the current keymap mode. This is actually the same as the current `main`. The real behavioral change is related to the following config `keymap_mode`:

The keymap mode with which the Atuin search is started is controlled by the config `keymap_mode`. When `keymap_mode` is not specified, the keymap mode on the startup is determined based on the shell's keymap that started the Atuin search. When the config `keymap_mode` is specified, the keymap mode on the startup is forced to be the specified one.

@YummyOreo @ellie What do you think of this interface? If you have another idea, I can adjust the PR.

### CODE REVIEW

**Comment by Nemo157** [comment]
Nice, that works about how I'd expect. I wonder if the generated key-bindings should be changed based on vim-mode too. Currently the `^r` binding overrides the "redo" binding from zsh's normal-mode, and `k`/`/` seem much more familiar bindings to use. I also assume these widgets are internal API so I shouldn't really be binding to them directly.

**Comment by akinomyoga** [comment]
I thought about it again, and I think another option for the configuration interface would be to provide a single configuration `keymap_mode = { "emacs" (default) | "vim-insert" | "vim-normal" | "auto" }` instead of `vim` (i.e. remove `vim`). By making `emacs` default, it doesn't change the behavior for the existing users. When the user wants the automatic determination of the startup keymap mode, the user can specify `keymap_mode = "auto"`. When the user wants to always start the Atuin search with the vim-normal mode, the user can specify `keymap_mode = "vim-normal"`.

**Comment by akinomyoga** [comment]
> I thought about it again, and I think another option for the configuration interface would be

I implemented in the latest commit 96eeca0. I feel this is cleaner, though we have discussed the global config `vim` plus another config in #1553. The default value is `emacs` to keep the behavior for the existing users unchanged. The users who would like the Atuin search to always start with the vim-normal mode can specify `keymap_mode = "vim-normal"` instead of the current way `vim = true`. The users who would like the automatic determination of the startup keymap of the Atuin search can specify `keymap_mode = "auto"`.

**Review by ellie — APPROVED** [review]
Looks good to me, thank you!

Would you also be able to update the [docs](https://github.com/atuinsh/docs) please?

**Comment by ellie** [comment]
ah and the shellcheck

**Comment by akinomyoga** [comment]
Thank you! I've fixed SC2048, rebased on top of the latest `main`, and squashed trivial commits.

**Comment by akinomyoga** [comment]
I opened https://github.com/atuinsh/docs/pull/8 in atuin/docs.

**Pull request merged**
