### PR TITLE
fix atuin-daemon optional dependency

### PR DESCRIPTION
**Pull request by panekj**
## Checks
- [x] I am happy for maintainers to push small adjustments to this PR, to speed up the review cycle
- [x] I have checked that there are no existing pull requests for the same thing

### CODE REVIEW

**Comment by ellie** [comment]
Hey! Looks like this one isn't building - would you be able to fix the issue please?

**Comment by panekj** [comment]
> Hey! Looks like this one isn't building - would you be able to fix the issue please?

I forgot to put `atuin-daemon` in feature flag (yeah, I'm smart like that)

**Comment by panekj** [comment]
btw. daemon is currently broken on Windows, it cannot be compiled (which is the reason behind this PR)

**Comment by ellie** [comment]
Thank you!

**Review by ellie — APPROVED** [review]

**Pull request merged**
