### PR TITLE
fix(dotfiles): fish alias import

### PR DESCRIPTION
**Pull request by ellie**
## Checks
- [ ] I am happy for maintainers to push small adjustments to this PR, to speed up the review cycle
- [ ] I have checked that there are no existing pull requests for the same thing

### CODE REVIEW

**Comment by ellie** [comment]
Ah, that's embarassing 🤦‍♀️ 

Fix in #1974. Sorry about that, should be good now.

**Comment by rigrig** [comment]
Yups, parsing works ok now! :tada:

**Comment by rigrig** [comment]
Sorry, cheered too soon: it's now generating a bunch of errors on shell start :-(


```fish
alias: -o: unknown option
alias: expected <= 2 arguments; got 3
alias: -u: unknown option
alias: expected <= 2 arguments; got 3
alias: --color=auto: unknown option
alias: -e: unknown option
alias: -e: unknown option
alias: -e: unknown option
alias: -p: unknown option
alias: -p: unknown option
alias: -p: unknown option
alias: -p: unknown option
alias: --autoremove: unknown option
alias: --recursive: unknown option
alias: --tree: unknown option
alias: --brief: unknown option
alias: expected <= 2 arguments; got 3
alias: expected <= 2 arguments; got 3
alias: expected <= 2 arguments; got 3
alias: --icons: unknown option
alias: -a: unknown option
alias: --icons: unknown option
alias: --no-mtime: unknown option
```

From these aliases:
```fish
$ atuin dotfiles alias list
config='/usr/bin/git --git-dir=$HOME/.dotfiles.git/ --work-tree=$HOME'
docker-vabo='docker compose -p vabo -f /home/richard/src/php/vabo/ontwikkel/docker/docker compose.yml'
exa='exa --icons --level=2 --git --header'
fgrep='fgrep --color=auto'
gcm='git checkout master && git pull'
gfa='git fetch --all --prune --tags'
git_push_skip_ci='git push -o ci.skip'
gsu='git submodule update'
idl='python3 ~/src/instagram-media-downloader/instagram.py -u'
install='please apt install'
ip='ip --color=auto'
please=doas
po-artisan='docker compose exec -e PHP_IDE_CONFIG="serverName=po.test" beheer-72 php /project/beheer/artisan'
po-make='docker compose exec -e PHP_IDE_CONFIG="serverName=po.test" beheer-72 make'
po-run='docker compose exec -e PHP_IDE_CONFIG="serverName=po.test" beheer-72'
po2-artisan='docker compose -p po2 exec -e PHP_IDE_CONFIG="serverName=127.0.0.1" web php ./artisan'
po2-format='docker compose -p po2 exec web composer run format'
po2-run='docker compose -p po2 exec -e PHP_IDE_CONFIG="serverName=127.0.0.1" web'
po2-run-as-root='docker compose -p po2 exec -u root:root -e PHP_IDE_CONFIG="serverName=127.0.0.1" web'
remove='please apt purge --autoremove'
rsync='rsync --recursive --partial --progress --human-readable --info=progress2'
tree='exa --tree -L3 --classify --git --icons  --group-directories-first'
uc='unicode --brief --max (math (tput lines) - 5) --regex'
update-bangle='ssh berilia "cd /var/www/BangleApps/bin/ && git pull && git submodule update && ./publish.sh"'
update-nella='ssh nella ./dockers/update-all.sh'
which=command
wine32='WINEARCH=win32 WINEPREFIX=$HOME/.wine32 wine'
x='exa --icons --git --classify --group-directories-first'
xa='x -a'
xdebug='export XDEBUG_CONFIG="remote_enable=1 remote_mode=req remote_port=9000 remote_host=127.0.0.1 remote_connect_back=0"'
xl='exa --icons --git --classify --long --header  --group-directories-first'
ydl='youtube-dl --no-mtime --prefer-free-formats --audio-format opus --merge-output-format mp4'
```

**Comment by ellie** [comment]
Does ` ~/.local/share/atuin/dotfiles/cache/aliases.fish` look correct?

**Comment by rigrig** [comment]
Looks like the opening/closing quotes got doubled for all aliases containing spaces:
```fish
alias config=''/usr/bin/git --git-dir=$HOME/.dotfiles.git/ --work-tree=$HOME''
alias docker-vabo=''docker compose -p vabo -f /home/richard/src/php/vabo/ontwikkel/docker/docker compose.yml''
alias exa=''exa --icons --level=2 --git --header''
alias fgrep=''fgrep --color=auto''
alias gcm=''git checkout master && git pull''
alias gfa=''git fetch --all --prune --tags''
alias git_push_skip_ci=''git push -o ci.skip''
alias gsu=''git submodule update''
alias idl=''python3 ~/src/instagram-media-downloader/instagram.py -u''
alias install=''please apt install''
alias ip=''ip --color=auto''
alias please='doas'
alias po-artisan=''docker compose exec -e PHP_IDE_CONFIG="serverName=po.test" beheer-72 php /project/beheer/artisan''
alias po-make=''docker compose exec -e PHP_IDE_CONFIG="serverName=po.test" beheer-72 make''
alias po-run=''docker compose exec -e PHP_IDE_CONFIG="serverName=po.test" beheer-72''
alias po2-artisan=''docker compose -p po2 exec -e PHP_IDE_CONFIG="serverName=127.0.0.1" web php ./artisan''
alias po2-format=''docker compose -p po2 exec web composer run format''
alias po2-run=''docker compose -p po2 exec -e PHP_IDE_CONFIG="serverName=127.0.0.1" web''
alias po2-run-as-root=''docker compose -p po2 exec -u root:root -e PHP_IDE_CONFIG="serverName=127.0.0.1" web''
alias remove=''please apt purge --autoremove''
alias rsync=''rsync --recursive --partial --progress --human-readable --info=progress2''
alias tree=''exa --tree -L3 --classify --git --icons  --group-directories-first''
alias uc=''unicode --brief --max (math (tput lines) - 5) --regex''
alias update-bangle=''ssh berilia "cd /var/www/BangleApps/bin/ && git pull && git submodule update && ./publish.sh"''
alias update-nella=''ssh nella ./dockers/update-all.sh''
alias which='command'
alias wine32=''WINEARCH=win32 WINEPREFIX=$HOME/.wine32 wine''
alias x=''exa --icons --git --classify --group-directories-first''
alias xa=''x -a''
alias xdebug=''export XDEBUG_CONFIG="remote_enable=1 remote_mode=req remote_port=9000 remote_host=127.0.0.1 remote_connect_back=0"''
alias xl=''exa --icons --git --classify --long --header  --group-directories-first''
alias ydl=''youtube-dl --no-mtime --prefer-free-formats --audio-format opus --merge-output-format mp4''
```

**Comment by rigrig** [comment]
For the record: quoting was fixed with bf88b42cec26ee2912c5e25eaadd5764b3a480f0, fish aliases seem to work properly now :tada:

**Comment by ellie** [comment]
Wooo! Glad it's sorted 🎉

**Pull request merged**
