### PR TITLE
replace chrono with time

### PR DESCRIPTION
**Pull request by conradludgate**
Kinda useless, but I've wanted to do this one for a while nice. In my opinion, `time` has a much cleaner (and safer by design) API compared to `chrono`.

Still need to test and review everything

### CODE REVIEW

**Comment by ellie** [comment]
👀

**Review by ellie — DISMISSED** [review]
LGTM! Merge when ready 🚀

**Comment by ellie** [comment]
#1218 is blocked on chrono deprecations now being errors - are we able to merge this soon? Before I go and fix them all 🙃

**Comment by conradludgate** [comment]
Sure, go for it

**Pull request merged**
