### PR TITLE
fix(gui): add support for checking if the cli is installed on windows

### PR DESCRIPTION
**Pull request by YummyOreo**
On windows, this makes the default shell `powershell` and adds support for checking if atuin is installed on windows in the gui
## Checks
- [x] I am happy for maintainers to push small adjustments to this PR, to speed up the review cycle
- [x] I have checked that there are no existing pull requests for the same thing

### CODE REVIEW

**Review by ellie — APPROVED** [review]
Excellent - thank you so much!

I'm still pretty surprised that's all we needed for Windows. I'm doing a bunch more with ptys fairly soon which I imagine _might_ break things more though 😢

**Comment by CarterLi** [comment]
Just find this in the changelog of the latest release. Does it mean that we now support Windows?

**Comment by YummyOreo** [comment]
> Just find this in the changelog of the latest release. Does it mean that we now support Windows?

Tentatively. It builds, but there isnt a powershell plugin yet (but there is a nushell plugin).

**Comment by ellie** [comment]
It will usually build and run on Windows thanks to @YummyOreo's work, but we don't really have the bandwidth (time, hardware, etc) to test and support it properly.

**Comment by CarterLi** [comment]
I'll have a try

**Comment by CarterLi** [comment]
image

It works!

**Comment by CarterLi** [comment]
This is a binary if someone don't want to built it himself. Don't know why it's so large though

[atuin.zip](https://github.com/user-attachments/files/15973911/atuin.zip)

**Pull request merged**
