### PR TITLE
Custom Styling

### PR DESCRIPTION
**Pull request by kolektiv**
As mentioned in #1153 - I've had a quick little play at a simple way for people to set styles. I've tried to make it fairly minimal rather than introduce a whole theme system or something similar. Some things to note:
* I've just used Ratatui colors as a basic component.
    * That means that atuin-client now needs a dependency on Ratatui (but I don't think that's an issue; it's a dependency of crates which already have it).
    * Ratatui color deserialization was very basic indeed (only named colors) until 0.26, after which it supports hex (RGB) and indexed colors, so I've moved Ratatui to a workspace dependency and bumped the version (haven't tested for side effects!)
* Styles can be set under a new `styles` table in the config. I've currently implemented support for two styles, just as a proof - the command in the history list, and the selected command in the history list. They can be set something like the following (obviously, compact table notation is also fine):
```toml
[styles]
command = "#555555"

[styles.command_selected]
bold = true
foreground = "#90fa00"
```
* Style values can be of two kinds (as seen above):
    * A simple color value, in which case it will be treated as the foreground color.
    * A table of style properties which make up a style, and which consists of...
        * foreground (color)
        * background (color)
        * underline (color)
        * bold (bool)
        * crossed_out (bool)
        * italic (bool)
        * underlined (bool)
    * Properties which are not set will not be set on the style (there is currently no inheritance, etc.)

Here's how that particular configuration looks in my terminal (using the compact style).

Screenshot 2024-02-26 at 16 46 51

Opinions/objections are welcome. Obviously, a couple of slight structural tweaks are needed, but I've tried to avoid anything too invasive.

## Checks
- [x] I am happy for maintainers to push small adjustments to this PR, to speed up the review cycle
- [x] I have checked that there are no existing pull requests for the same thing

### CODE REVIEW

**Comment by kolektiv** [comment]
Hold off on reviewing this, changes have been lost on the way...

**Comment by kolektiv** [comment]
OK this is pretty representative of the proposed approach now I think, seems fairly straightforward.

**Comment by tessus** [comment]
I think this needs a rebase.

**Comment by kolektiv** [comment]
> I think this needs a rebase.

Yes, probably so @tessus - I'm very out of practice with git and forks these days, if you let me know what to run I'll do it!

**Comment by tessus** [comment]
in the main branch you have to run `git pull upstream main` (replace `upstream` with the name of the remote for the atuin repo, not your fork).
Then switch to your branch and do a `git rebase main`
After that a `git push -f` is required.

That should do it.

**Comment by tessus** [comment]
Hmm, I just tried myself and something seems off. You removed code that is currently in main. A rebase won't fix this.

P.S.: Ah, you also didn't create your own branch. So that could explain it. I am afraid the PR can't be merged as is. You might have to interactively rebase and remove the commit where you merged main into your main. Let me try to see, if I can fix this.

**Comment by kolektiv** [comment]
Ah hmm - I let GitHub do some kind of sync - I'll look into it in the morning, and see if I can work out how to fix it up.

**Comment by tessus** [comment]
I tried several things including cherry-picking your commits. I think one would have to go through all your commits and undo the removal of the code you did.

**Comment by tessus** [comment]
342384593dd662ec757ebca1bb5a7ee25c5c2f0c is the commit that removes code that shouldn't be removed

**Comment by kolektiv** [comment]
I'll close this pull request and create a non-broken one for simplicity!

**Pull request closed without merging**
