### PR TITLE
Add config setting for showing tabs

### PR DESCRIPTION
**Pull request by digital-cuttlefish**
From https://github.com/atuinsh/atuin/issues/1754

Yet to do local testing, but this is what I had in mind.

## Checks
- [x] I am happy for maintainers to push small adjustments to this PR, to speed up the review cycle
- [x] I have checked that there are no existing pull requests for the same thing

### CODE REVIEW

**Comment by tessus** [comment]
I like the idea, but I think the name of the config option is a bit off. It sounds that atuin won't show any tabs anymore. If you don't read the explanation that is.

I'd opt for a name like `show_tab_info` or something along those lines. But that's just me.

**Comment by digital-cuttlefish** [comment]
Oh, I actually wanted the tabs themselves to be hidden.
Where should I look for that?

**Comment by tessus** [comment]
No, your code is perfectly fine afaik by looking at it. I haven't tested it, but it looks fine.
I only mentioned that the option name you used `show_tabs` is a bit ambiguous - at least for me. But maybe I am wrong. Let's see what the devs have to say.

**Review by ellie — APPROVED** [review]
I get @tessus' point about show_tabs being a little ambiguous, but I'm happy with this as-is due to how it matches nicely with show_help.

If you could also make a PR to the docs, that would be great! https://github.com/atuinsh/docs

Seeing as this is your first time contributing, if you would like a holographic contributors-only Atuin sticker, then please fill out this [form!](https://notionforms.io/forms/contributors-stickers)

We do also have a [Discord](https://discord.gg/Fq8bJSKPHh) if you'd like to ask any questions, or just fancy hanging out!

**Comment by digital-cuttlefish** [comment]
https://github.com/atuinsh/docs/pull/47

**Pull request merged**
