### PR TITLE
chore: setup git cliff

### PR DESCRIPTION
**Pull request by ellie**
Thanks @orhun! This is really nice.

### CODE REVIEW

**Comment by ellie** [comment]
later: add it to CI

**Comment by orhun** [comment]
Aye, great! There are [fancier templates](https://github.com/orhun/git-cliff/blob/main/cliff.toml), just let me know if need help with tweaking anything!

**Comment by ellie** [comment]
> Aye, great! There are [fancier templates](https://github.com/orhun/git-cliff/blob/main/cliff.toml), just let me know if need help with tweaking anything!

will definitely check them out! the default (plus linking PRs) is great already though 🙏  thanks!

**Comment by orhun** [comment]
more cool GitHub stuff are coming in https://github.com/orhun/git-cliff/pull/363 🚀

**Pull request merged**
