### PR TITLE
Customizable Themes

### PR DESCRIPTION
**Pull request by philtweir**
### What does this PR do?

Adds theming, extensible via TOML.

The following features are implemented:

* two sample built-in themes in addition to the default colours
* colours can be defined by [palette names](https://ogeon.github.io/docs/palette/master/palette/named/index.html)
* ability to add new TOML-defined themes to config directory
* meaning-based theming, so colours are requested based on the purpose (loglevel / type of text)
* designed for including general styles in future (for now, focused on colours)
* fallbacks, with (by default) unobtrusive erroring to limit consequences of theme issues
* configuration through config.toml

Adds dependencies to atuin-client for:
* crossterm: for styles
* palette: for named colours
* lazy_static: for defining built-in themes
* strum: for consistently defining enum maps in TOML
* [DEV] testing_logger: ensuring that log output is correct in debug mode

TODO (once code/configuration signed off):
* tidy commit history

### Screenshots

Screenshot from 2024-07-08 00-24-11
Screenshot from 2024-07-08 00-26-11
Screenshot from 2024-07-08 00-26-06

*Note*: there is a PR (#1785) for custom styles, but as that was not ready when I was looking a few months back and I had a little time, I put this together for my own use -- PRing based on [feedback in the forum](https://forum.atuin.sh/t/can-the-colors-be-changed/51/8?u=philtweir). 

## Checks
- [x] I am happy for maintainers to push small adjustments to this PR, to speed up the review cycle
- [x] I have checked that there are no existing pull requests for the same thing

### CODE REVIEW

**Review by ellie — COMMENTED** [review]
This looks really good, thank you! Breaking things down into meanings makes sense, though we'll need to ensure it's clear in docs how that is categorised

I like the named colour approach, however it's likely we will get a feature request for RGB codes. Palette seems to support that and it doesn't look hard to add here, but what are your thoughts there? Not necessarily required right now though.

Otherwise, could we get a few more tests please? It would be nice to ensure that fallbacks on error work as intended, etc.

**Comment by philtweir** [comment]
> This looks really good, thank you! Breaking things down into meanings makes sense, though we'll need to ensure it's clear in docs how that is categorised

Yes, indeed - makes sense.
 
> I like the named colour approach, however it's likely we will get a feature request for RGB codes. Palette seems to support that and it doesn't look hard to add here, but what are your thoughts there? Not necessarily required right now though.

I have tried adding hexcode support, and if the string starts with ``#`, it will attempt to parse it into three numbers. I could not see a convenience function in palette (might just be me being daft) so have done that with `u8::from_str_radix` to save pulling anything new in, and seems to work fine.

> Otherwise, could we get a few more tests please? It would be nice to ensure that fallbacks on error work as intended, etc.

Yes, indeed - was keen to get a general go-ahead, so will come back with docs & additional tests!

**Comment by philtweir** [comment]
Few changes:

* a number of tests added
* ability to base one theme on another (this seemed like a big QoL improvement on copying an entire file, to aid uptake)
* fallbacks for Meanings, so more can be added without old themes defaulting weirdly
* documentation first draft here: https://github.com/atuinsh/docs/pull/66
* improved the structure of the theme file, so it can have a name in it
* moved from `println` to `log` so that we can test debug output

**Review by ellie — APPROVED** [review]
Nice one! Super happy for this to go in. I appreciate the easy-to-review commits as well, thank you

Seeing as this is your first time contributing, if you would like a holographic contributors-only Atuin sticker, then please fill out this [form!](https://notionforms.io/forms/contributors-stickers)

We do also have a [Discord](https://discord.gg/Fq8bJSKPHh) if you'd like to ask any questions, or just fancy hanging out!

**Comment by philtweir** [comment]
Thanks @ellie - much appreciated and thanks again for all your hard work on Atuin! It's been brilliant for me day-to-day, so glad to help and hope this feature works well for others. Will keep an eye for any related bugs/requests.

**Pull request merged**
