### PR TITLE
feat(bash): provide auto-complete source for ble.sh

### PR DESCRIPTION
**Pull request by akinomyoga**
I saw #1479 for the zsh-autosuggestions integration. A similar setup is possible with ble.sh.

### CODE REVIEW

**Comment by ellie** [comment]
Thank you! Love to see ble.sh filling in the gaps with Bash

Would you be able to update the "integrations" docs page with this please?

https://github.com/atuinsh/atuin/blob/main/docs/docs/integrations.md

**Comment by akinomyoga** [comment]
> Would you be able to update the "integrations" docs page with this please?
> 
> https://github.com/atuinsh/atuin/blob/main/docs/docs/integrations.md

Sure! I haven't noticed the doc page. Thank you for pointing it.

**Review by ellie — APPROVED** [review]
Excellent! Thank you 🙏

**Comment by akinomyoga** [comment]
Thank you for checking! And, sorry. I've just amended it; I've replaced the last period with a colon.

**Review by ellie — APPROVED** [review]

**Comment by arcuru** [comment]
@akinomyoga We actually had chatted about this in the Atuin Discord, we weren't sure if ble.sh would support this but we were going to ping you to ask. Thanks for beating us to it :)

**Comment by akinomyoga** [comment]
@arcuru Yeah, I actually noticed it in Discord afterward. Thank you for your comment!

**Pull request merged**
