### PR TITLE
Support importing from replxx history files

### PR DESCRIPTION
**Pull request by amosbird**
As discussed in Discord, this feature should be useful for managing history of applications which use https://github.com/AmokHuginnsson/replxx . One notable example would be ClickHouse.

I'll try to integrate atuin into clickhouse-client later.

## Checks
- [X] I am happy for maintainers to push small adjustments to this PR, to speed up the review cycle
- [X] I have checked that there are no existing pull requests for the same thing

### CODE REVIEW

**Comment by ellie** [comment]
Thank you! Would it be possible to get some test cases for this please?

**Comment by amosbird** [comment]
Sure. Tests have been added.

**Review by ellie — APPROVED** [review]
looks good, thank you! :shipit:

**Comment by ellie** [comment]
Seeing as this is your first time contributing, if you would like a holographic contributors-only Atuin sticker, then please fill out this [form!](https://notionforms.io/forms/contributors-stickers)

We do also have a [Discord](https://discord.gg/Fq8bJSKPHh) if you'd like to ask any questions, or just fancy hanging out!

**Comment by amosbird** [comment]
> if you would like a holographic contributors-only Atuin sticker, then please fill out this form!

That sounds perfect! I've completed the form.

**Pull request merged**
