### PR TITLE
feat(keyup): Configure SearchMode for KeyUp invocation #1216

### PR DESCRIPTION
**Pull request by deicon**
Adding another config option to setup Search Mode on KeyUp invocations.
Fixing #1216

### CODE REVIEW

**Comment by deicon** [comment]
@ellie not sure about the review process here, but PRs seem to be alive quite a bit. 
Do you need some more Info for this PR to ease the review ?

Awesome tool by the way :-) appreciate your work here.

**Comment by ellie** [comment]
All good! I was halfway through testing your PR but then had to start work 🤣

It didn't quite work on my setup, but mine is pretty non standard. I'll get some time to finish the review over the weekend

**Comment by deicon** [comment]
Updated the documentation as seen in this PR #1235 which seems to be a copy of this one here.

**Comment by bretthoerner** [comment]
I have a dupe PR up, and my guess as to why this didn't work for Ellie is that you need to change the `engine`: https://github.com/atuinsh/atuin/pull/1235/files#diff-8ef1f8bf3ed66b4786b6e33de018a22448799f64470de843ce9c7653e69b5eddR645

**Comment by deicon** [comment]
@bretthoerner thanks for the catch. Which makes our PRs identical :)

**Comment by ellie** [comment]
It'll just need a `cargo fmt` and should be good to go

**Comment by deicon** [comment]
fmt and clippy fixed

**Review by ellie — APPROVED** [review]

**Pull request merged**
